[Interface]
Address = 10.0.0.2/24
PrivateKey = $(cat /etc/wireguard/privatekey)

[Peer]
PublicKey = znXAE8AJXS3GGajQ40lFlYUwphiWKDS7mLNWA8fzsA0=
Endpoint = 34.175.8.33:51820
AllowedIPs = 10.0.0.0/24, 172.26.0.0/24
PersistentKeepalive = 25
